
# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipgo
    username: admin
    password: p@ssword
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

jwt:
  secret-key: 027eb3f4aa36e178497290da0fa573ee
  expire-length: 60480000000000000

oauth:
  kakao:
    client-id: 027eb3f4aa36e178497290da0fa573ee
    redirect-uri: http://localhost:3000/login

cloud:
  aws:
    s3:
      bucket: 버킷이름
      zipgo-directory-name: 집고_디렉토리_이름
      pet-image-directory: 집고_디렉토리_이미지
      image-url: 집고_이미지_서버_유알엘

