spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zipgo
    username: root
    password: rkdudmysql4_
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
