---
# port
server:
  port: 8081

---
# database
spring:
  config:
    import: classpath:/env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
# jpa
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  sql:
    init:
      mode: never

---
# OAUTH
oauth:
  kakao:
    client-id: ${CLIENT_ID}
    redirect-uri: ${REDIRECT_URI}
    client-secret: ${CLIENT_SECRET}

---
# jwt
jwt:
  secret-key: ${ZIPGO_SECRET_KEY}
  access-token-expire-length: ${ACCESS_TOKEN_EXPIRE_LENGTH}
  refresh-token-expire-length: ${REFRESH_TOKEN_EXPIRE_LENGTH}

---
# aws
cloud:
  aws:
    s3:
      bucket: ${WOOTECO_BUCKET}
      zipgo-directory: ${ZIPGO_DIRECTORY}
      env: ${ENVIRONMENT_DIRECTORY}
      image-url: ${ZIPGO_IMAGE_URL}

