DELETE http://localhost:8081/reviews/136/helpful-reactions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiaWF0IjoxNjkyMzMxMjY4LCJleHAiOjE2OTI5MzYwNjh9.Y8On1cHV3g7zMNL0sJA5Un-kfaL0NlYToEDY77boDKI
