name: Frontend Deploy

on:
  push:
    branches: [develop, feature/#382]
    # paths: frontend/**

jobs:
  build-dockerfile:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build -t ${{ secrets.FRONTEND_IMAGE_NAME }}:$GITHUB_RUN_NUMBER --platform linux/amd64,linux/arm64 . --load
          docker tag ${{ secrets.FRONTEND_IMAGE_NAME }}:$GITHUB_RUN_NUMBER ${{ secrets.FRONTEND_IMAGE_NAME }}:latest
        env:
          DOCKER_CLI_AGGREGATE: 1
          DOCKER_BUILDKIT: 1

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.FRONTEND_IMAGE_NAME }}:latest
        env:
          DOCKER_CLI_AGGREGATE: 1

  deploy-to-develop-EC2:
    needs: build-dockerfile
    runs-on: self-hosted

    steps:
      - name: Deploy to Develop EC2
        run: |
          docker stop ${{ secrets.FRONTEND_CONTAINER_NAME }} || true
          docker rm ${{ secrets.FRONTEND_CONTAINER_NAME }} || true
          docker pull ${{ secrets.FRONTEND_IMAGE_NAME }}:latest
          docker run -d -p 3000:3000 --name ${{ secrets.FRONTEND_CONTAINER_NAME }} ${{ secrets.FRONTEND_IMAGE_NAME }}:latest

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 프론트엔드 배포 알림
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
